include:
  - project: 'IsyFact/isy-gitlabci-templates'
    file: '/maven/.gitlab-ci-maven.yml'

build:doc:
  extends: .maven-build
  variables:
    MAVEN_BUILD_OPTS: -Pbuild-style-guide
  artifacts:
    expire_in: 2 day
    paths:
      - 'target/styleguide/**'

package:
  extends: .maven-package

deploy:
  extends: .maven-deploy

stages:
  - build
  - package
  - deploy
