include:
  - project: 'IsyFact/isy-gitlabci-templates'
    file: '/maven/.gitlab-ci-maven.yml'

stages:
  - package
  - deploy

package:
  extends: .maven-package
  dependencies:
  artifacts:
    paths:
      - "target/docs/**"
    expire_in: 2 days

deploy:
  extends: .maven-deploy

