include:
  - project: 'IsyFact/isy-gitlabci-templates'
    file: '/maven/.gitlab-ci-maven.yml'

stages:
  - build
  - package
  - deploy

build:
  extends: .maven-build

build:docs:
  extends: .maven-build
  variables:
    MAVEN_BUILD_OPTS: -P build-documentation
  artifacts:
    expire_in: 1 day
    paths:
      - '**/target/docs/**'

package:
  extends: .maven-package

deploy:
  extends: .maven-deploy
