variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s settings.xml --batch-mode --errors --fail-at-end"

image: $BUILDIMAGE
stages:
  - buildstage
  - teststage
  - packagestage
  - deploystage

cache:
  paths:
   - .m2/repository
  key: "ifecache"

.template: &vorlage
  tags:
   - ZIII4
  before_script:
   - mvn -v
   - echo "$SETTINGSSECURITY" > ~/.m2/settings-security.xml


.doctemplate : &docvorlage
  image: ruby:2.5
  stage: buildstage
  tags:
   - ZIII4
  script:
   - cat /proc/version
   - gem install asciidoctor-pdf --pre
   - asciidoctor-pdf -v
   - cd src/main/asciidoc/styleguide
   - asciidoctor -b html5 -a revnumber=$(ruby -r rexml/document -e 'puts REXML::Document.new(File.new(ARGV.shift)).elements["/project/parent/version"].text' ../../../../pom.xml) -a revdate=$(date +"%d.%m.%Y") -a icons=font -a sectanchors -a idprefix -a docinfo1 -a data-uri -a stylesdir=../theme -a stylesheet=isyfact.css master.adoc -o styleguide.html
   - asciidoctor-pdf -a revnumber=$(ruby -r rexml/document -e 'puts REXML::Document.new(File.new(ARGV.shift)).elements["/project/parent/version"].text' ../../../../pom.xml) -a revdate=$(date +"%d.%m.%Y") -a icons=font -a sectanchors -a idprefix -a docinfo1 -a pdf-stylesdir=../theme -a pdf-style=isyfact -a pdf-fontsdir=../theme/fonts/ master.adoc -o styleguide.pdf


build:docs:
  <<: *docvorlage
  artifacts:
   paths:
    - "src/main/asciidoc/styleguide/*.pdf"
    - "src/main/asciidoc/styleguide/*.html"
   expire_in: 1 week
  only:
   - branches
  except:
   - schedules

build:docs_schedule:
  <<: *docvorlage
  artifacts:
   paths:
    - "src/main/asciidoc/styleguide/*.pdf"
    - "src/main/asciidoc/styleguide/*.html"
   expire_in: 2 days
  only:
   - schedules

build:
  <<: *vorlage
  stage: buildstage
  artifacts:
   paths:
    - "target/*"
   expire_in : 6 h
  script:
   - rm -rf .m2/repository/de
   - mvn -U $MAVEN_CLI_OPTS compile
  except:
   - schedules

test:
  <<: *vorlage
  stage: teststage
  artifacts:
   paths:
    - "target/surefire-reports/*"
    - "target/site/*"
   reports:
    junit:
     - "target/surefire-reports/TEST-*.xml"
   when: always
  dependencies:
   - build
  script:
   - mvn $MAVEN_CLI_OPTS org.jacoco:jacoco-maven-plugin:prepare-agent -Dmaven.surefire.argline='@{argLine} -Xmx1g -Dfile.encoding=${project.build.sourceEncoding}' test org.jacoco:jacoco-maven-plugin:report
  after_script:
   - mkdir -p src/site
   - echo "<project name=\"IsyFact Erweiterungen\"></project>" > src/site/site.xml
   - mvn $MAVEN_CLI_OPTS surefire-report:report-only
   - mvn -DgenerateReports=false $MAVEN_CLI_OPTS site
   - '[[ -f ./target/site/jacoco/index.html ]] && echo Code coverage:$(egrep "([0-9]{1,3}%)" ./target/site/jacoco/index.html -o -h |  head -1)'
  except:
   - schedules

package:
  <<: *vorlage
  stage: packagestage
  dependencies:
   - build
  script:
   - mvn $MAVEN_CLI_OPTS -Dmaven.test.skip=true package
  except:
   - schedules

deploy:
  <<: *vorlage
  stage: deploystage
  dependencies:
   - build
  script:
   - mvn $MAVEN_CLI_OPTS -Dmaven.test.skip=true -Dmaven.install.skip=true deploy
  except:
   - schedules
