[bibliography]
== Literaturverweise
- [[[DetailkonzeptKomponenteDatenzugriff]]] +
  Detailkonzept Komponente Datenzugriff +
  10_Blaupausen\technische_Architektur\Detailkonzept_Komponente_Datenzugriff.pdf
- [[[KonzeptFehlerbehandlung]]] +
  Konzept Fehlerbehandlung +
  20_Bausteine\Fehlerbehandlung\Konzept_Fehlerbehandlung.pdf
- [[[KonzeptLogging]]] +
  Konzept Logging +
  20_Bausteine\Logging\Konzept_Logging.pdf
- [[[NutzungsvorgabenSicherheit]]] +
  Nutzerdokumentation Sicherheit +
  20_Bausteine\Sicherheitskomponente\Nutzungsvorgaben_Sicherheit.pdf
- [[[Vorlageanwendung]]] +
  IsyFact-Vorlageanwendung "Terminfindung" +
  https://github.com/IsyFact/IsyFact-Vorlageanwendung
- [[[CommonEL]]] +
  Common Expression Language +
  http://commons.apache.org/el/
- [[[Facelets]]] +
  Facelets +
  https://facelets.dev.java.net/
- [[[JPA]]] +
  Java Persistence API +
  http://java.sun.com/javaee/overview/faq/persistence.jsp
- [[[OWASP10]]] +
  OWASP Top 10 Project +
  https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project
- [[[Spring]]] +
  Spring Framework Reference Documentation +
  http://docs.spring.io/spring-framework/docs/4.2.x/spring-framework-reference/html/
- [[[SUNRI]]] +
  SUN Referenzimplementierung JSF +
  http://java.sun.com/javaee/javaserverfaces/
- [[[SWF]]] +
  Spring Web Flow Dokumentation +
  http://static.springsource.org/spring-webflow/docs/2.4.x/reference/html/
- [[[Tomahawk]]] +
  Apache JSF Komponentenbibliothek +
  http://myfaces.apache.org/tomahawk/index.html
- [[[WikiJSF]]] +
  JavaServer Faces +
  http://de.wikipedia.org/wiki/JavaServer_Faces
- [[[IsyFactJQuery]]] +
  Paketierte JQuery-Dateien für IsyFact-Anwendungen +
  60_Software\Bibliotheken\web-gui
- [[[Styleguide]]] +
  Styleguide +
  20_Bausteine\Styleguide\Styleguide.pdf
- [[[TomcatNutzungskonzept]]] +
  Nutzungskonzept Apache Tomcat +
  30_Plattform\Nutzungskonzept_Apache_Tomcat_8.pdf
